service: AppConfig

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    MESSAGE:
      prod: "This is production environment"
      dev: "This is development environment"
  users-role: arn:aws:iam::338756162532:role/ARCMSLambda
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    MESSAGE: ${self:custom.myEnvironment.MESSAGE.${self:custom.myStage}}
    CANDIDATE_TABLE: arcms-brandUserOrders-${self:custom.myStage}
    IMAGE_BUCKET: looc-cloud-images
    STAGE: ${self:custom.myStage}
    ACCESS_STORE: store
    ACCESS_MANAGER: manager
    ACCESS_ADMIN: admin

package:
  individually: true
  exclude:
    - "**/*"
    - node_modules/**

functions:
  get:
    handler: appconfig.get
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get the app config, by default returns live, if specified the testing one
    package:
      include:
        - appconfig.js
        - shared/**
    events:
      - http:
          path: /{brand}/appconfig
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true

  new:
    handler: appconfig.new
    role: ${self:custom.users-role}
    memorySize: 512
    description: Post a new app configuration, overwriting the old testing one
    package:
      include:
        - appconfig.js
        - shared/**
    events:
      - http:
          path: /{brand}/appconfig
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:eu-central-1:338756162532:userpool/eu-central-1_Qg8GXUJ2v

  publish:
    handler: appconfig.publish
    role: ${self:custom.users-role}
    memorySize: 512
    description: Copy the current testing config to production
    package:
      include:
        - appconfig.js
        - shared/**
    events:
      - http:
          path: /{brand}/appconfig/publish
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:eu-central-1:338756162532:userpool/eu-central-1_Qg8GXUJ2v
