service: ARCMS-Emails # NOTE: update this with your service name
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    MESSAGE:
      prod: "This is production environment"
      dev: "This is development environment"
  users-role: arn:aws:iam::338756162532:role/ARCMSLambda
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    NEWORDERTOPIC: new-glasses-order-${self:custom.myStage}
    REQUESTDXFTOPIC: create-dxf-for-order-${self:custom.myStage}
    MESSAGE: ${self:custom.myEnvironment.MESSAGE.${self:custom.myStage}}
    CANDIDATE_TABLE: arcms-brandUserOrders-${self:custom.myStage}
    IMAGE_BUCKET: looc-cloud-images
    MODEL_BUCKET: ar-glasses-models
    STAGE: ${self:custom.myStage}
    ACCESS_STORE: store
    ACCESS_MANAGER: manager
    ACCESS_ADMIN: admin

package:
  individually: true
  exclude:
    - "**/*"
    - node_modules/**

functions:
  send-new-order-mails:
    handler: emails/emails.newOrder
    role: ${self:custom.users-role}
    memorySize: 512
    description: Send email notifications when new order is received
    package:
      include:
        - emails/**
        - templates/**
        - node_modules/mustache/mustache.min.js
        - brand_settings.json
    events:
      - sns: ${self:provider.environment.NEWORDERTOPIC}

  create-dxf-files:
    handler: emails/dxffilemail.newRequest
    role: ${self:custom.users-role}
    memorySize: 2048
    timeout: 300
    description: Send email with a number of created dxf files for the ordered frames
    package:
      include:
        - emails/**
        - brand_settings.json
        - node_modules/**
    events:
      - sns: ${self:provider.environment.REQUESTDXFTOPIC}

  cognito-verification-email:
    handler: emails/cognito.verification
    role: ${self:custom.users-role}
    memorySize: 512
    description: Send email with verification code for password reset
    package:
      include:
        - emails/**
        - templates/**
        - node_modules/mustache/mustache.min.js
        - brand_settings.json
        - brand_texts.json