service: MATERIALS
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom:
  myStage: ${opt:stage, self:provider.stage}
  myEnvironment:
    MESSAGE:
      prod: "This is production environment"
      dev: "This is development environment"
  users-role: arn:aws:iam::338756162532:role/ARCMSLambda

provider:
  name: aws
  stage: dev
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    CANDIDATE_TABLE: arcms-brandUserOrders-${self:custom.myStage}
    IMAGE_BUCKET: looc-cloud-images
    STAGE: ${self:custom.myStage}
    ACCESS_STORE: store
    ACCESS_MANAGER: manager
    ACCESS_ADMIN: admin

package:
  individually: true
  exclude:
    - "**/*"
    - node_modules/**

functions:
  get:
    handler: materials.get
    role: ${self:custom.users-role}
    memorySize: 512
    description: Get an array of materials, optionally filtered by type, paginated
    package:
      include:
        - materials.js
        - shared/**
        - brand_settings.json
    events:
      - http:
          path: /{brand}/materials
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true

  new:
    handler: materials.new
    role: ${self:custom.users-role}
    memorySize: 512
    description: Post the configuration for a new material
    package:
      include:
        - materials.js
        - shared/**
        - brand_settings.json
    events:
      - http:
          path: /{brand}/materials
          method: post
          cors: true
          request:
            parameters:
              paths:
                brand: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:eu-central-1:338756162532:userpool/eu-central-1_Qg8GXUJ2v

  delete-material:
    handler: materials.delete
    role: ${self:custom.users-role}
    memorySize: 512
    description: Delete material should the current user have enough rights
    package:
      include:
        - materials.js
        - shared/**
        - brand_settings.json
    events:
      - http:
          path: /{brand}/materials/{type}/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                brand: true
                type: true
                id: true
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:eu-central-1:338756162532:userpool/eu-central-1_Qg8GXUJ2v
